# Generated by Django 4.0.3 on 2022-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='facilitator',
            field=models.CharField(default='Ryerson', max_length=200),
            preserve_default=False,
        ),
    ]
